# Generated by Django 6.0.3 on 2026-04-01 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_cliente_producto_alter_pedido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 1, 18, 44, 17, 582450, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
